# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Data Science Fun
email: dataninja.me@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  R, 파이썬(Python), 데이터 과학 (data science) 이야기.
  실리콘밸리 데이터과학자 권재명 (Jaimie Kwon) 의 홈페이지입니다.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://jaimyoung.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: "http://dataninja.me" # the base hostname & protocol for your site, e.g. http://example.com

# hide .html extensions cf. https://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:day/:title/

twitter_username: jaimyoung
github_username:  jaimyoung
facebook_username:  jaimie.kwon
facebook_username2:  dataninja.me
linkedin_username:  statkwon

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  ipds-kr:
    output: true
    permalink: /ipds-kr/:path/

plugins:
  - jekyll-redirect-from


# Disqus Comments per https://github.com/jekyll/minima
disqus:
  shortname: jaimyounggithubio

# Google Analytics
google_analytics: UA-5745444-4
